[package]
name = "fimprints"
version = "0.1.0"
authors = ["Colin Wallace <colin@mooooo.ooo>"]

[dependencies]
fs_extra = "1.1"
handlebars = "0.32"
pathdiff = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
structopt = "0.2"
toml = "0.4"
