# Links to iisaw's print books are enumerated here: https://www.fimfiction.net/blog/650533/print-versions-of-my-fanfics
fimfic_id = 264005
order_url = 'http://www.lulu.com/shop/iisaw/the-twilight-enigma/hardcover/product-22800704.html'
thumb_path = 'thumb'

author = 'iisaw'
title = 'The Twilight Enigma'
synopsis = "Twilight sets out to learn more of the ways of the world, and soon decides that the whole planet is disorganized, insanely dangerous, and desperately needs to be fixed. And she's just the mare to do it... with a little help from her friends. Also, there are sky-pirates!"
