fimfic_id = 141549
order_url = 'http://www.lulu.com/shop/iisaw/the-celestia-code/hardcover/product-23154141.html'
thumb_path = 'thumb'

author = 'iisaw'
title = 'The Celestia Code'
synopsis = 'Test book.'
