# Links to iisaw's print books are enumerated here: https://www.fimfiction.net/blog/650533/print-versions-of-my-fanfics
fimfic_id = 141549
order_url = 'http://www.lulu.com/shop/iisaw/the-celestia-code/hardcover/product-23154141.html'
thumb_path = 'thumb'

author = 'iisaw'
title = 'The Celestia Code'
synopsis = 'Princess Twilight Sparkle discovers a centuries-old mystery hidden in the Royal Archives. Her investigation leads through layer after layer of deception and misdirection, setting her hooves on a path that seems to be leading to a mysterious secret. Along the way, she learns that some friendships can be very, very strange.'
