fimfic_id = 175385
order_url = 'http://www.lulu.com/shop/iisaw/the-luna-cypher/hardcover/product-22790267.html'
thumb_path = 'thumb'

author = 'iisaw'
title = 'The Luna Cypher'
synopsis = "When the monsters created by the dark crystal engine escape their prison, it's up to Princess Twilight Sparkle to deal with them. She gets help and advice from Princess Luna, but things don't go as planned. In fact, when a pony who relies on logic and rationality tries to navigate the stormy seas of emotional entanglement while simultaneously saving Equestria from a horde of evil creatures intent on destroying everything they encounter, nothing goes as planned."
